### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by kyusuncho** [immortalCO/NeuralEditor#1]
Congratulations on having your paper accepted for CVPR 2023!

May I know when the code is available?

**Comment by hanxuel** [comment]
Thank you for your excellent work of 'NeuralEditor: Editing Neural Radiance Fields via Manipulating Point Clouds'.  I would also like to know when will the code and data be released?

**Comment by jaidevshriram** [comment]
Just following up on this - since CVPR is now over, are there plans to release the code soon? Thanks!
