### ISSUE TITLE
Issue running run_ns.py

### ISSUE THREAD

**Issue by pavelgolikov** [immortalCO/NeuralEditor#2]
Hi, I am trying to run `run_ns.py` file to train the NeRF and I am running into some trouble. I downloaded NeRF synthetic dataset from the original authors and modified the script to see the files. When the script tries to read the cloud:

`pth = torch.load(f"{DATASET}/{CLOUD_NAME}.pth")`

it can't find the pth file. From what I understand this is the point cloud. How can I obtain that point cloud?

Best Regards,

Pavel.

**Comment by immortalCO** [comment]
Hi, thank you for your question.

The point cloud here is the initial point cloud generated by PointNeRF's MVSNet. Please download the pre-processed datasets from https://drive.google.com/drive/folders/1cwB8jfmxMetNITRrve8hZE5ZleQLqKsW?usp=sharing (now uploading, files will be gradually appearing, please wait a few minutes) which includes these point clouds.

Sorry for the inconvenience.

**Comment by pavelgolikov** [comment]
Oh no problem. Thank you for fast response. I was able to download the dataset from the drive. I did run into another little issue: When I am trying to run the same file: run_ns.py, it runs for a while and produces output, but eventually arrives at an unresolved import:

https://github.com/immortalCO/NeuralEditor/blob/9ebd3f19dac7b4c259c00e0dd613ecb16abb5f2e/run_ns.py#L787C27-L787C27

The line seems to be importing a multi_field file. I looked and that file doesn't seem to be in the repo. Would it be possible to get it please?

Best Regards,

Pavel.

**Comment by immortalCO** [comment]
Hi,
The `multi_field` import is a part of legacy code and is not used after importing in `run_ns.py`. Please just remove that line. We have also updated `run_ns.py` to remove this line.

Thanks.

**Comment by pavelgolikov** [comment]
Got it thank you very much. It is training now. I have another quick question: I am running run_ns.py on 3090 and training seems very slow. I have been training overnight and it says it is at epoch 7 out of 110 epochs. Is that normal?

**Comment by immortalCO** [comment]
Hi, 

Each of the training epochs is not equivalent - the first around 15 epochs contains the optimization of the point cloud, which will run very slowly; while the rest 95 epochs are not optimizing the point cloud anymore, and will be very fast. Therefore, it should be normal if the first 15 epochs are very slow.

Thanks.

**Comment by pavelgolikov** [comment]
I see. Thank you so much. We are very interested in inference for this workload. Would you mind sharing the pre-trained models for some scenes like chair, hotdog, lego, and mic for example?
