### ISSUE TITLE
Issue running Deform_mic.ipynb

### ISSUE THREAD

**Issue by pavelgolikov** [immortalCO/NeuralEditor#3]
Hi, I am running Deform_mic.ipynb and running into a problem, cell 64 on line 2:

`deform_pts = torch.load(f"./datasets/Deform/{DEFORM}.{VER}.pth")['pts'].float().cuda()`

errors out claiming that it can't find Deform directory. I looked and indeed  I don't have Deform directory inside. I raised the previous issues about run_ns, so I have datasets directory, but not Deform subdirectory. Would you mind sharing those files please?

Best Regards

**Comment by immortalCO** [comment]
Hi,

The `Deform` folder is where I put deformed point clouds w.r.t. specific checkpoints. If you have trained your model, you will need to generate the deformed point clouds w.r.t. your checkpoints. The point clouds in different checkpoints are different.

Please refer to our benchmark at https://drive.google.com/drive/folders/1XRxGUJHWx-7plFx4L30cjseLMhq9zTlV?usp=sharing to see how to create the deformed point cloud with the benchmark deformations (or your own ones), then let `deform_pts` be that file (.npy file is also acceptable).

Thanks.

**Comment by pavelgolikov** [comment]
Thank you. I am running into more errors running this notebook. I have changed the scene from mic to chair. I have a trained chair checkpoint (110 epochs) which I used and I have used chair_cloud.1027.pth (from the google drive link above) as the point cloud in the notebook (cell 69).

![image](https://github.com/immortalCO/NeuralEditor/assets/40681739/02b5831a-cca7-482d-ac9c-520828b2f4e7)

Am I using the wrong checkpoint?

**Comment by pavelgolikov** [comment]
Regarding the instructions from the above link:

- Go to the `hotdog` folder.
- Obtain your point cloud. If you are using a mesh-based method, you can just use the mesh vertices as the point cloud.
- Generate the mesh `hotdog.ply` (an example is attached for a quick start) from your point cloud using the script in the last email from your point cloud. Please use `pts2ply.py`.
- Save a copy of `hotdog.orig.blend` and then open it.
- Run the Blender script `mesh_deform`. You can see how the deformation works in this script.
- After that, you can see both the scene and the mesh of the point cloud deformed in the window. In the same time, the deformed point cloud `hotdog.npy` will be saved in the folder.
- Optionally, you can generate the ground truth views by running Blender script `360_view.py`.

I have several questions about the above instructions. Let us start with the first one:
1. "Obtain your point cloud." How do I obtain the point cloud? I have just used run_ns.py to train the network for "chair" scene. I have trained for 110 epochs. I have the checkpoint.

**Comment by immortalCO** [comment]
Hi,

Sorry for the unclear descriptions. I have just updated that folder with corrected instructions.

For the "obtain point cloud", I have provided a new code `ckpt2pts.py` to extract point clouds from your trained `ckpt` files, and the output can be used towards `pts2ply.py`. `ckpt2pts.py` just uses `torch.save` to save the point cloud in a `pth` file.

Thanks

**Comment by pavelgolikov** [comment]
No problem at all. Thank you for your fast response. I am running into a little bit more trouble here. In Blender I am trying to run `mesh_deform` script, but getting this error:

![image](https://github.com/immortalCO/NeuralEditor/assets/40681739/2dfc044c-3e2a-4464-a8bd-0c76e75520e2)

I looked for that operator in bpy and couldn't find it. I tried to use the only one available for import mesh: "bpy.ops.import_mesh.stl" (https://docs.blender.org/api/current/bpy.ops.import_mesh.html), but then I get the following error:

![image](https://github.com/immortalCO/NeuralEditor/assets/40681739/307da018-bf87-4c1e-983b-569672ca927e)

Could you please take a look.

Best Regards,

Pavel.

**Comment by immortalCO** [comment]
Hi,

You should run the script in Blender, instead of copying it out of Blender and run in python. 

In order to do this, please select `mesh_deform` in blender, then click on the “▶” to run.
![1703039795050](https://github.com/immortalCO/NeuralEditor/assets/22522323/6a6f3f02-9a4b-4384-aa76-bf35c92412ac)

Also, please make sure your `ply` file's name is `mic.ply` in the `mic` folder.

Thanks.

**Comment by pavelgolikov** [comment]
I see. I am still getting an error though:

![image](https://github.com/immortalCO/NeuralEditor/assets/40681739/afaa76f2-b30a-4ddb-a9e3-c215f531b9b8)

And when I use .stl instead of .ply in import_mesh call, I get this:

![image](https://github.com/immortalCO/NeuralEditor/assets/40681739/9c6cc07b-6619-4e1a-8196-066385fbdc27)

**Comment by immortalCO** [comment]
Hi,

For debugging purpose, would you please try to use the provided `mic.ply` provided in the folder, to see if there is any issue? It works well on my computer with no issue.

Thanks.

**Comment by pavelgolikov** [comment]
Hi,

Here is me trying the original script on mic.ply file that was provided:

![image](https://github.com/immortalCO/NeuralEditor/assets/40681739/3b7c333f-ee84-4fc7-9c28-fc723b171f81)

Here is the script when I change pky to stl:

![image](https://github.com/immortalCO/NeuralEditor/assets/40681739/d10eaf13-60a5-4362-b401-71f620714fc4)

It doesn't seem to be able to find bpy.ops.import_mesh.stl. Indeed, when I look at bpy.ops documentation, this function is not there: https://docs.blender.org/api/current/bpy.ops.import_mesh.html. The only function listed is .stl.

**Comment by immortalCO** [comment]
Hi,

I have located the issue, which is related to the Blender version. Please use Blender 3.3 instead of 4.0.

Thanks.

**Comment by pavelgolikov** [comment]
I see. Thank you very much!
